import type { ClipData } from "../App";

export const mockClips: ClipData[] = [
  {
    id: "clip-1",
    content_type: "text",
    text_content: "Hello, world! This is a plain text clip.",
    html_content: null,
    image_path: null,
    source_app: "firefox",
    source_app_icon: null,
    content_hash: "abc123",
    content_size: 41,
    metadata: null,
    pinboard_id: null,
    is_favorite: false,
    created_at: new Date(Date.now() - 120000).toISOString(), // 2 min ago
    accessed_at: null,
    access_count: 0,
  },
  {
    id: "clip-2",
    content_type: "code",
    text_content: 'fn main() {\n    println!("Hello");\n}',
    html_content: null,
    image_path: null,
    source_app: "vscode",
    source_app_icon: null,
    content_hash: "def456",
    content_size: 38,
    metadata: '{"language":"Rust"}',
    pinboard_id: null,
    is_favorite: false,
    created_at: new Date(Date.now() - 300000).toISOString(), // 5 min ago
    accessed_at: null,
    access_count: 0,
  },
  {
    id: "clip-3",
    content_type: "link",
    text_content: "https://example.com/page",
    html_content: null,
    image_path: null,
    source_app: "chrome",
    source_app_icon: null,
    content_hash: "ghi789",
    content_size: 24,
    metadata: '{"url":"https://example.com/page","title":"Example Page"}',
    pinboard_id: null,
    is_favorite: false,
    created_at: new Date(Date.now() - 3600000).toISOString(), // 1 hour ago
    accessed_at: null,
    access_count: 3,
  },
  {
    id: "clip-4",
    content_type: "image",
    text_content: null,
    html_content: null,
    image_path: "/tmp/paste/images/clip-4.png",
    source_app: "gimp",
    source_app_icon: null,
    content_hash: "jkl012",
    content_size: 102400,
    metadata: '{"format":"png","size_bytes":102400}',
    pinboard_id: null,
    is_favorite: false,
    created_at: new Date(Date.now() - 86400000).toISOString(), // 1 day ago
    accessed_at: null,
    access_count: 0,
  },
  {
    id: "clip-5",
    content_type: "file",
    text_content: "/home/user/documents/report.pdf",
    html_content: null,
    image_path: null,
    source_app: "nautilus",
    source_app_icon: null,
    content_hash: "mno345",
    content_size: 30,
    metadata: null,
    pinboard_id: null,
    is_favorite: true,
    created_at: new Date(Date.now() - 604800000).toISOString(), // 7 days ago
    accessed_at: null,
    access_count: 1,
  },
];
